AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  backend

  Sample SAM Template for backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.signuphandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      Events:
        SignUpApi:
          Type: Api
          Properties:
            Path: /signup
            Method: post
      # Environment:
      #   Variables:
      #     BUCKET_NAME: !Ref aeroservicessignup

  # SignUpBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: testsignup

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
          - ""
          - - ApplicationInsights-SAM-
            - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
          - ""
          - - ApplicationInsights-SAM-
            - Ref: AWS::StackName
      AutoConfigurationEnabled: "true"
    DependsOn: ApplicationResourceGroup
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  SignUpApi:
    Description: URL for the SignUp function API endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/signup/"

  SignUpFunction:
    Description: SignUp Lambda Function ARN
    Value: !GetAtt SignUpFunction.Arn
  SignUpFunctionIamRole:
    Description: Implicit IAM Role created for SignUp function
    Value: !GetAtt SignUpFunctionRole.Arn
